apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xa57xutf7-python 
  janus-idp.io/tekton: xa57xutf7-python
  backstage.io/kubernetes-id: xa57xutf7-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xa57xutf7-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  